version: '3'
services:
  toxiproxy:
    image: shopify/toxiproxy
    container_name: toxiproxy
    ports:
      - "8474:8474"   # Toxiproxy API port
      - "8081:8081"   # Toxiproxy proxy port
    command: ["toxiproxy-server"]

  http_service:
    build: .
    container_name: http_service
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
    depends_on:
      - toxiproxy
    networks:
      - default
    links:
      - toxiproxy
